version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - java-webapp
      - react-ui
      - python-service1
      - python-service2

  java-webapp:
    image: openjdk:18-jre-slim
    container_name: java-webapp
    build:
      context: ./java-webapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  react-ui:
    image: node:14
    container_name: react-ui
    build:
      context: ./react-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  python-service1:
    image: python:3.9-slim
    container_name: python-service1
    build:
      context: ./python-service1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

  python-service2:
    image: python:3.9-slim
    container_name: python-service2
    build:
      context: ./python-service2
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    command: ["python", "app.py"]

networks:
  default:
    driver: bridge
